numProducers: 1
numConsumers: 1
numPartitionsPerTopic: 1
indexConfig:
    minX: 33.7757
    minY: 84.3963
    maxX: 33.9757
    maxY: 84.5963
    blockSize: 0.01
    indexType: GEOHASH
locationChangeInterval: 1
payloadFile: payload-1Kb.data
pulsarConfigFile: pulsar.yaml
producerTrajectoryFiles:
    - "0.0_0.txt"
consumerTrajectoryFiles:
    - "1.0_0.txt"   

