numProducers: 1
numConsumers: 1
numPartitionsPerTopic: 1
indexConfig:
    minX: 33.7757
    minY: 84.3963
    maxX: 34.7757
    maxY: 85.3963
    blockSize: 0.01
    indexType: RTREE
locationChangeInterval: 1000
payloadFile: payload-1Kb.data
pulsarConfigFile: pulsar.yaml
producerTrajectoryFiles:
    - "0.0_0.txt"
consumerTrajectoryFiles:
    - "0.0_0.txt"   
testDurationSeconds: 30
outputFile: "output_10sec_1prod_1cons.json"
